name: PNG to SVG

on:
  push:
    paths:
      - 'icon/**/*.png'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y imagemagick potrace

      - name: Convert PNG to SVG
        run: |
          find icon -type f -name "*.png" | while read file; do
            svg="${file%.png}.svg"
            pgm="${file%.png}.pgm"

            convert "$file" -threshold 70% "$pgm"
            potrace "$pgm" -s -o "$svg"
            rm "$pgm"

            echo "Converted $file -> $svg"
          done

      - name: Commit & Push
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"

            git add icon
            git commit -m "chore: auto convert png to svg"
            git push
          else
            echo "No changes"
          fi
